### ISSUE TITLE
Vurdere alternativ til objektserialisering for å holde tilstand

### ISSUE THREAD

**Issue by glennbech** [difi/difi-deploy-manager#6]
Applikasjonen lagrer intern tilstand ved objektserialisering. Hvis vi endrer på noen av klassene i en release, vil applikasjonen ikke kunne restartes.

**Comment by mhoel** [comment]
Er denne relevant lenger?

**Comment by Steinbjarne** [comment]
nei

**Comment by mhoel** [comment]
:+1: da lukker jeg denne
